version: "3"

services:
  mysql:
    build: ./database/bin/mysql
    container_name: '5.7-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./database/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./database/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions

  api:
    build: ./server/
    container_name: 'finances-explorer-api'
    restart: 'always'
    links:
      - mysql
    ports:
      - "8888:8888"
    environment:
      MYSQL_HOST_NAME: mysql